version: 2.1
jobs:
  build:
    docker:
      - image: longkaka/gitlabci-rsync # Use the appropriate image
    steps:
      - checkout  # This step checks out your project's code
      - run:
          name: Execute deploy.sh
          command: |
            bash sh deploy.sh