version: 2.1
jobs:
  build:
    docker:
      - image: longkaka/gitlabci-rsync # Use the appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Install sshpass
          command: |
             apt-get update
             apt-get install -y sshpass
             which sshpass
      - run:
          name: Deploy to VPS
          command: |
            bash deploy.sh
